# Generated by Django 5.2.12 on 2026-03-27 05:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=300, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=300)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=500)),
                ('file', models.FileField(blank=True, upload_to='pdfs/')),
                ('folder_path', models.CharField(blank=True, help_text='Absolute path for folder-imported PDFs', max_length=1000)),
                ('source_type', models.CharField(choices=[('folder', 'Imported from folder'), ('upload', 'Uploaded by user')], default='folder', max_length=10)),
                ('page_count', models.IntegerField(default=0)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pipeline.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_id', models.CharField(max_length=20)),
                ('page_num', models.IntegerField()),
                ('note_ix', models.IntegerField()),
                ('text', models.TextField()),
                ('text_hash', models.CharField(max_length=32)),
                ('signal_score', models.IntegerField(default=0)),
                ('is_low_value', models.BooleanField(default=False)),
                ('needs_llm', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='pipeline.pdfdocument')),
            ],
            options={
                'ordering': ['document', 'page_num', 'note_ix'],
            },
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('extracting', 'Extracting text'), ('triaging', 'Triaging notes'), ('llm_processing', 'LLM processing'), ('merging', 'Merging mentions'), ('qc', 'Quality check'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('model_id', models.CharField(default='Qwen/Qwen2.5-1.5B-Instruct', max_length=200)),
                ('use_4bit', models.BooleanField(default=True)),
                ('total_pdfs', models.IntegerField(default=0)),
                ('processed_pdfs', models.IntegerField(default=0)),
                ('total_notes', models.IntegerField(default=0)),
                ('resolved_notes', models.IntegerField(default=0)),
                ('unresolved_notes', models.IntegerField(default=0)),
                ('total_mentions', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('documents', models.ManyToManyField(blank=True, related_name='runs', to='pipeline.pdfdocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('label', models.CharField(max_length=200)),
                ('value', models.TextField()),
                ('normalized_value', models.TextField(blank=True)),
                ('date_text', models.CharField(blank=True, max_length=100)),
                ('certainty', models.CharField(default='unknown', max_length=20)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('evidence_quote', models.TextField(blank=True)),
                ('source_pages', models.JSONField(blank=True, default=list)),
                ('evidence_ids', models.JSONField(blank=True, default=list)),
                ('origin', models.CharField(choices=[('regex', 'Deterministic regex'), ('llm', 'LLM extraction'), ('merged', 'Merged')], default='regex', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentions', to='pipeline.noteledger')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='pipeline.patient')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='pipeline.pdfdocument')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentions', to='pipeline.pipelinerun')),
            ],
            options={
                'ordering': ['category', 'date_text', 'label'],
            },
        ),
        migrations.CreateModel(
            name='FinalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_count', models.IntegerField(default=0)),
                ('note_count', models.IntegerField(default=0)),
                ('mention_count', models.IntegerField(default=0)),
                ('category_count', models.IntegerField(default=0)),
                ('grouped_record', models.JSONField(default=dict)),
                ('review_flags', models.JSONField(default=list)),
                ('traceability', models.JSONField(default=dict)),
                ('stats', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_record', to='pipeline.patient')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.pipelinerun')),
            ],
            options={
                'ordering': ['patient__code'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('stage', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pipeline.pipelinerun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_num', models.IntegerField()),
                ('text', models.TextField(blank=True)),
                ('selected_source', models.CharField(default='native', max_length=10)),
                ('char_count', models.IntegerField(default=0)),
                ('word_count', models.IntegerField(default=0)),
                ('alpha_ratio', models.FloatField(default=0.0)),
                ('need_ocr', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='pipeline.pdfdocument')),
            ],
            options={
                'ordering': ['document', 'page_num'],
                'unique_together': {('document', 'page_num')},
            },
        ),
    ]
