# Generated by Django 5.2.13 on 2026-05-18 11:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalrecord',
            name='relation_graph',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='finalrecord',
            name='timeline_events',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mention',
            name='evidence_artifact_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='noteledger',
            name='artifact_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='noteledger',
            name='layout_hint',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pageledger',
            name='layout_blocks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pageledger',
            name='page_height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pageledger',
            name='page_width',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='folder_path',
            field=models.CharField(blank=True, help_text='Absolute filesystem path for folder-imported PDFs', max_length=1000),
        ),
        migrations.CreateModel(
            name='DocumentArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(choices=[('text_block', 'Text block'), ('text_line', 'Text line'), ('table', 'Table'), ('header', 'Header'), ('footer', 'Footer'), ('stamp', 'Stamp'), ('signature', 'Signature'), ('handwriting', 'Handwriting'), ('figure', 'Figure'), ('image', 'Image'), ('page_region', 'Page region')], max_length=30)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('backend', models.CharField(blank=True, max_length=50)),
                ('text', models.TextField(blank=True)),
                ('normalized_text', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('bbox', models.JSONField(blank=True, default=list)),
                ('polygon', models.JSONField(blank=True, default=list)),
                ('page_num', models.IntegerField(default=0)),
                ('reading_order', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='pipeline.pdfdocument')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='pipeline.noteledger')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='pipeline.pageledger')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='pipeline.patient')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='pipeline.pipelinerun')),
            ],
            options={
                'ordering': ['document', 'page_num', 'reading_order', 'artifact_type'],
            },
        ),
        migrations.CreateModel(
            name='MentionRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('has_diagnosis', 'Has diagnosis'), ('treated_with', 'Treated with'), ('evidenced_by', 'Evidenced by'), ('test_result', 'Test result'), ('followed_by', 'Followed by'), ('related_to', 'Related to'), ('occurred_on', 'Occurred on'), ('progression', 'Progression')], max_length=40)),
                ('confidence', models.FloatField(default=0.0)),
                ('evidence_artifact_ids', models.JSONField(blank=True, default=list)),
                ('evidence_pages', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='pipeline.patient')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relations', to='pipeline.pipelinerun')),
                ('source_mention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_relations', to='pipeline.mention')),
                ('target_mention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_relations', to='pipeline.mention')),
            ],
            options={
                'ordering': ['patient__code', 'relation_type', 'created_at'],
            },
        ),
    ]
